server:
 port : 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false

    service-url:
      defaultzone: http://localhost:8989/eureka
    

  

    
 