server :
 port : 9191
 
 #spring.security.user.name=tom

#spring.security.user.password=tom@123

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/javabatch
   username: root
   password: temp1234
 jpa:
   hibernate:
    ddl-auto: update
